### ISSUE TITLE
Error on first run: ENOTSUP: operation not supported on socket, mkdir '/home/codewarrior'

### ISSUE THREAD

**Issue by adrienjoly** [Codewars/codewars-runner-cli#170]
I just cloned the repo locally, ran `npm install`, then `node run -l javascript -c "console.log(1+1)"` as provided in the README.

Got the following error:

```
/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/lib/shovel.js:73
        else throw ex;
             ^

Error: ENOTSUP: operation not supported on socket, mkdir '/home/codewarrior'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at mkdirParentSync (/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/lib/util.js:36:16)
    at module.exports.codeWriteSync (/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/lib/util.js:77:5)
    at run (/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/lib/shovel.js:61:9)
    at Object.start (/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/lib/shovel.js:34:9)
    at Object.run (/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/lib/runners/javascript.js:9:12)
    at module.exports.run (/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/lib/runner.js:5:50)
    at Object.<anonymous> (/Users/adrienjoly/Dev/WEEKEND/codewars-runner-cli/run.js:60:1)
    at Module._compile (module.js:398:26)
```

I'm using Node 5.3.0 on Mac OS X El Capitan.

Do you know what I should do to test this runner without error?

**Comment by adrienjoly** [comment]
Ok, nevermind.

After installing Docker, running the Quickstart Terminal, and following the project's Setup steps, I was able to run `node run -l javascript -c "console.log(1+1)"` from the Docker instance.
