### ISSUE TITLE
JVM Runner has issues with JavaFX?

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#309]
Here's a [Kumite](https://www.codewars.com/kumite/589b5f6656187495fe00002b?sel=589b5f6656187495fe00002b) about it.

It marks that the Class has not been compiled but shows no other warnings at all.

But if you change test code to

````
Aciago aciago = new Aciago();
````
it has no truble passing so I think it's leningen related.

**Comment by kazk** [comment]
I'm going to close this because we don't use `jvm-runner` for Java any more.

---

I'm not sure what was the problem with `jvm-runner`, but on `java-runner` the STDERR is:

```
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
```

some google search suggested `javafx` requires `GTK` on linux, but I don't know.

**Comment by javatlacati** [comment]
Quantum toolkit is the render library as far as I know. Perhaps you need some native libraries.
