### ISSUE TITLE
Java CLI testing cannibalizes stderr

### ISSUE THREAD

**Issue by brendanvos** [Codewars/codewars-runner-cli#374]
Started brushing up on my java and noticed it's particularly difficult to debug java in codewars.
I was working on [this kata](https://www.codewars.com/kata/resistor-color-codes-part-2/train/java) and found that often when my code produces an error part of that error gets displayed as testing output, and the rest of stderr goes missing.

I was using the default test cases and my code produced an error (found this by copying my solution and tests to eclipse):
```
java.lang.NumberFormatException: For input string: "4.7"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at EncodeResistorColors.encodeResistorColors(EncodeResistorColors.java:8)
	at EncodeResistorColorsTest.test(EncodeResistorColorsTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

However, here's the output I got on codewars:

![java stderr missing](https://cloud.githubusercontent.com/assets/11360165/24830691/ce0996c0-1c58-11e7-9715-b06ea526eb59.PNG)

The error trace is missing and the part of it gets displayed as if it were output from the assertEquals test (which it technically is... but not in the sense it's currently being treated).

**Comment by kazk** [comment]
Java now outputs "Exception Details" where you can click to expand.

![image](https://user-images.githubusercontent.com/639336/29481138-d7a5c28e-8432-11e7-946a-4f17c9a94edc.png)
![image](https://user-images.githubusercontent.com/639336/29481145-e5191542-8432-11e7-9e85-9b5d7d2fb5d2.png)
