### ISSUE TITLE
Elixir katas not working

### ISSUE THREAD

**Issue by DCrow** [Codewars/codewars-runner-cli#495]
Any elixir kata code execution returns this
```javascript
module.js:457
    throw err;
    ^

Error: Cannot find module './runners/elixir'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.run (/runner/lib/runner.js:3:10)
    at Object.<anonymous> (/runner/run-json.js:1:87)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by kazk** [comment]
Thanks for reporting.

@jhoffner This is probably because Elixir is now independent from `erlang-runner` and some deployments are out of sync for some reason. Sounds similar to how Node 8 wasn't available for Red users?

**Comment by jhoffner** [comment]
Yeah I'll do an audit, must be some stale instances hanging around somehow

**Comment by MarkPearlMYOB** [comment]
I'm getting the same issue...
