### ISSUE TITLE
Python assert_approx_equals throws error if argument is not number

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#760]
A simple `Test.assert_approx_equals([], 0, margin=0.01)` gives

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    Test.assert_approx_equals([], 0, margin=0.01)
  File "/runner/frameworks/python/cw-2.py", line 84, in assert_approx_equals
    div = max(abs(actual), abs(expected), 1)
TypeError: bad operand type for abs(): 'list'
```

So this method doesn't handle arguments properly and assumes that they are always like numbers.

**Comment by kazk** [comment]
Users can write a separate test to ensure it's a number.

`assertAlmostEqual` shipped with Python gives very similar result.
```
Traceback (most recent call last):
  File "test_unittest.py", line 5, in test_one
    self.assertAlmostEqual([], 0)
  File "/usr/lib/python3.7/unittest/case.py", line 883, in assertAlmostEqual
    diff = abs(first - second)
TypeError: unsupported operand type(s) for -: 'list' and 'int'
```
